apiVersion: apps/v1 
kind: Deployment
metadata:
  name: irisclone
spec:
  selector:
    matchLabels:
      app: irisclone
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: irisclone
    spec:
      containers:
      - image: store/intersystems/iris-community:2020.4.0.524.0
        name: iris
        env:
        - name: ISC_DATA_DIRECTORY
          value: /external/iris
        - name: ISC_CPF_MERGE_FILE
          value: /external/merge/merge.cpf
        ports:
        - containerPort: 52773
          name: smp-http
        volumeMounts:
        - name: iris-external-sys
          mountPath: /external
        - name: cpf-merge
          mountPath: /external/merge
        livenessProbe:
          initialDelaySeconds: 25
          periodSeconds: 10
          exec:
            command:
            - /bin/sh
            - -c
            - "iris qlist iris | grep running"
      volumes:
      - name: iris-external-sys
        persistentVolumeClaim:
          claimName: iris-pvc-restored
      - name: cpf-merge
        configMap:
          name: iris-cpf-merge